DROP DATABASE IF EXISTS geek_report;

CREATE DATABASE geek_report CHARACTER SET utf8;

USE geek_report;

DROP TABLE IF EXISTS datasource;
CREATE TABLE datasource (
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(60) NOT NULL,
dbname VARCHAR(30) NOT NULL,
driver_path VARCHAR(300) NOT NULL,
config TEXT,
project_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS project;
CREATE TABLE project (
id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(120) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
created_by INT NOT NULL
);
